#DML - SELECT
SELECT * FROM PRODUCT;

#WHERE - 조건
SELECT * FROM PRODUCT
WHERE PRODUCT_PRICE >= 50000; #자바 스트림의 FILTER와 비슷.

/*연산자 우선순위
() > NOT > [* , / , %] > [+ , - > = , <= , >= , < , > , BETWEEN , IN , LIKE , IS NULL] > [AND , OR] 
*/

#IN 사용.(노트북이거나 키보드)
SELECT * FROM PRODUCT
WHERE PRODUCT_NAME IN ("노트북" , "키보드");

INSERT INTO PRODUCT
VALUES (NULL , "노트북" , 1500000); # 중복 속성값 추가

#SELECT절에 DISTINCT 추가하면 중복값 제거
SELECT DISTINCT PRODUCT_NAME FROM PRODUCT;

#LIMIT. 상위 3줄만.
SELECT * FROM PRODUCT
LIMIT 3;

#ORDER BY. 오름차순 , 내림차순 정렬
SELECT * FROM PRODUCT
ORDER BY PRODUCT_PRICE DESC;

#0FFSET. 가격 비싼순서로 4,5,6등 추출
SELECT * FROM PRODUCT
ORDER BY PRODUCT_PRICE DESC
LIMIT 3 OFFSET 3;

#한 페이지에서 게시글 20개를 보여줄때 3페이지를 조회 - PAGINATION : LIMIT 20 OFFSET 20 * (PAGE - 1)

#가격 NULL인 상품 조회
SELECT * FROM PRODUCT
WHERE PRODUCT_PRICE IS NULL;

#숫자 범위 검색. 상품 가격 1만원 ~ 5만원. BETWEEN.
SELECT * FROM PRODUCT
WHERE PRODUCT_PRICE BETWEEN 10000 AND 50000;

#LIKE. 문자열 패턴검색
SELECT * FROM PRODUCT
WHERE PRODUCT_NAME LIKE "%북" OR "마__";

#(문제1)'~북'으로 끝나는 상품 조회.
 SELECT * FROM PRODUCT
 WHERE PRODUCT_NAME LIKE "%북";
 
#(문제2)가격이 3만원 ~ 10만원 사이 상품 조회.
SELECT * FROM PRODUCT
WHERE PRODUCT_PRICE BETWEEN 30000 AND 100000;

#(문제3) 5만원이상 상품들 중 가격이 높은순 조회.
SELECT * FROM PRODUCT
WHERE PRODUCT_PRICE >= 50000
ORDER BY PRODUCT_PRICE DESC;

#(문제4) 가격 높은순으로 중복 제거해서 5 ~ 8등 조회.
SELECT DISTINCT * FROM PRODUCT
ORDER BY PRODUCT_PRICE
LIMIT 4 OFFSET 4;

#ALIAS. 별칭.
SELECT PRODUCT_NAME AS '상품명' , PRODUCT_PRICE '상품 가격' , PRODUCT_PRICE * 1.1 AS '부가세' FROM PRODUCT;













