#WHERE 절 조건에 PRIMARY KEY 조건이 아니면 UPDATE가 실행되지 않는다 
#또한 LIMIT없이 UPDATE하는 경우도 UPDATE 실행 안됨-> 안전 업테이트 모드
#참고) 안전 업데이트 모드 ON/OFF
SET SQL_SAFE_UPDATES = 0; # 해제. 활성화는 1.

UPDATE PRODUCT SET PRODUCT_PRICE = 1600000
WHERE PRODUCT_ID = 1;

SELECT * FROM PRODUCT;

#CONCAT(A , B) : A와 B문자열을 이어 붙임.
UPDATE PRODUCT SET PRODUCT_NAME = CONCAT("[NEW] " , PRODUCT_NAME)
WHERE PRODUCT_ID = 1;

#SUBSTR(A , 7) 7번 인덱스 이전을 떼겠다. 
UPDATE PRODUCT SET PRODUCT_NAME = SUBSTR(PRODUCT_NAME , 7)
WHERE PRODUCT_ID = 1;

/*
UPDATE할때 반드시 SELECT로 확인하고 어떤 ROW가 업데이트 될지 확인하는걸 권장.
UPDATE PRODUCT SET PRODUCT_PRICE = * 1.1
WHERE PRODUCT_NAME LIKE "%메모리%";
위 코드 실행시 아래 코드로 먼저 확인 후 실행!!
SELECT * FROM PRODUCT
WHERE PRODUCT_NAME LIKE "%메모리%";
*/