/*
JOIN : 여러 테이블을 좌우로 연결해서 하나의 결과를 만드는 방법. 연결하는 역할 해주는게 FK.
#주문 + 고객 조회.
INNER JOIN : 두 테이블 모두에서 매칭되는 값이 있는 ROW만 가져옴.
ON : JOIN시킬 조건. O.CUSTOMER_ID = C.CUSTOMER_ID인것을 가져와라.
매칭 안될 경우 해당 ROW 가져오지 않음.
---ON과 WHERE차이
ON : 조인조건으로 두 테이블을 합쳐서 새로운 가상테이블을 만드는것.
WHERE : 테이블에 조건을 걸어 필터링.
*/
SELECT O.ORDER_ID , O.ORDER_DATE , O.CUSTOMER_ID , C.CUSTOMER_NAME 
FROM ORDERS O INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID;

# 주문(ORDERS) + 주문상세(ORDER_DETAILS) + 상품이름(PRODUCT)
 SELECT O.ORDER_ID , O.ORDER_DATE , O.CUSTOMER_ID , C.CUSTOMER_NAME , P.PRODUCT_NAME
 FROM ORDERS O INNER JOIN CUSTOMER C ON O.CUSTOMER_ID = C.CUSTOMER_ID
			   INNER JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
			   INNER JOIN PRODUCT P ON OD.PRODUCT_ID = P.PRODUCT_ID;
			            
#LEFT JOIN : 왼쪽 테이블은 모두 가져오고 오른쪽 테이블은 매칭되는 것만.(우측에 NULL 표시)
#고객이 주문했는지 여부 : CUSTOMERS LEFT JOIN ORDERS
SELECT C.CUSTOMER_NAME , O.ORDER_ID , O.ORDER_DATE # CUSTOMER LEFT JOIN ORDERS -> 전체 고객기준으로 ORDERS 데이터를 붙히겠다. 
FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

#(문제1)모든 주문에 대해 (ORDERS 테이블 시작) ORDER_ID , CUSTOMER_NAME , PRODUCT_NAME , QUANTITY 조회.
SELECT O.ORDER_ID , C.CUSTOMER_NAME , P.PRODUCT_NAME , QUANTITY 
FROM ORDERS O INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
			  INNER JOIN PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
              INNER JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID;

#ORDERS LEFT JOIN CUSTOMERS -> ORDERS 에는 주문한 고객 ID만 기재
INSERT INTO CUSTOMERS (CUSTOMER_NAME , CUSTOMER_PHONE , CUSTOMER_ADDRESS)
VALUES ('박화목' , '010-1111-2222' , '부산 금정구');              

#고객이 주문을 했는지 여부 파악하고 싶다. 고객(이) 니까 고객 기준.(FROM CUSTOMERS)
#LEFT JOIN 한 이유 : INNER JOIN하면 주문이 있는 고객만 추출. LEFT JOIN하면 모든 고객들 데이터는 남아있음 -> 주문없음 상태 추출가능.(NULL로 표현됨.)
SELECT * FROM CUSTOMERS C LEFT JOIN ORDERS O ON  C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL; # ORDER_ID가 NULL -> 주문 안했다.

#고객별 총 주문 금액(상품가격 * 주문수량) 집계. 고객별 이니까 고객기준.(FROM CUSTOMERS)
SELECT C.CUSTOMER_ID  , C.CUSTOMER_NAME , SUM(P.PRODUCT_PRICE * OD.QUANTITY) AS 'TOTAL_ORDER_PRICE'
FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
				 INNER JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
				 INNER JOIN PRODUCT P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_ID , C.CUSTOMER_NAME;

#상품별 주문 수(ORDER_DETAILS) 출력. 상품별 이니까 상품기준.(FROM PRODUCT)
#PRODUCT LEFT JOIN ORDER_DETAILS -> 왜 LEFT JOIN? 상품별 주문수 -> 주문이 없는(0인) 상품도 함께 추출해야되니까.
SELECT P.PRODUCT_ID , P.PRODUCT_NAME , COUNT(OD.ORDER_ID) AS 'ORDER_COUNT' # ORDER_DETAILS 의 한 ROW가 한번의 주문횟수를 의미.
FROM PRODUCT P LEFT JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_ID , P.PRODUCT_NAME;

#주문이 한번도 없는 상품 조회.
SELECT * FROM PRODUCT P LEFT JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
WHERE OD.ORDER_ID IS NULL;

#가장 많이 팔린 상품 조회.
SELECT P.PRODUCT_NAME , SUM(OD.QUANTITY) AS 'SOLD_PRODUCT' 
FROM PRODUCT P INNER JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY SOLD_PRODUCT DESC
LIMIT 1;

/*FK 제약. CONSTRAINT.
1.RESTRICT : 부모 테이블의 행이 삭제되거나 수정될 때 , 자식 테이블에 FK가 존재하면 작업 허용하지 않겠다. -> 권장.
부모 테이블의 PK의 ROW를 하나 삭제 할 때 , 자식 테이블의 FK에서는 삭제를 제한. -> 자식테이블의 FK먼저 삭제 후 부모테이블의 PK 삭제하자.
2.CASCADE : 부모가 삭제 , 업데이트 되면 자식 FK값도 자동으로 삭제 , 업데이트 함.
서버에 주석으로 CASCADE 내용을 문서화 하는게 중요. SET NULL도 마찬가지. 
3.SET NULL : 부모가 삭제 , 업데이트 되면 자식 FK값을 NULL로 변경.(자식테이블에 NOT NULL 아닌경우)
*/



						
















