/*
VIEW : 가상테이블. 실제 데이터 저장 x.
JOIN을 많이 하면 SELECT문이 번잡해짐. 또한 매번 똑같은 JOIN을 해야하는 경우가 생김.
JOIN결과를 미리 이름을 지어서 저장할 가상테이블이 필요. 
*/
#ORDERS + CUSTOMERS + ORDER_DETAILS + PRODUCT의 INNER JOIN 결과를 VIEW로 저장.
CREATE VIEW ORDER_FULL_VIEW AS
SELECT O.ORDER_ID , O.ORDER_DATE , C.CUSTOMER_ID , C.CUSTOMER_NAME , C.CUSTOMER_PHONE , C.CUSTOMER_ADDRESS ,
	   OD.ORDER_DETAIL_ID , OD.PRODUCT_ID , OD.QUANTITY , P.PRODUCT_NAME , P.PRODUCT_PRICE
FROM ORDERS O INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
			  INNER JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
			  INNER JOIN PRODUCT P ON OD.PRODUCT_ID = P.PRODUCT_ID;

#VIEW는 쿼리를 저장한 것. -> ORDER_FULL_VIEW를 SELECT하면 위 쿼리를 실행.
#편리하지만 성능이 떨어질 수 있음. 권장 -> VIEW에 JOIN 하지말자. 하더라도 하나만.
SELECT * FROM ORDER_FULL_VIEW;

#VIEW + GROUP BY
SELECT PRODUCT_ID , PRODUCT_NAME , SUM(QUANTITY) AS 'SOLD_COUNT'
FROM ORDER_FULL_VIEW
GROUP BY PRODUCT_ID , PRODUCT_NAME;







